// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetClinic.Data;

namespace PetClinic.Data.Migrations
{
    [DbContext(typeof(PetClinicDbContext))]
    [Migration("20190721190230_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetClinic.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "901 Messerschmidt Circle",
                            City = "Katwijk",
                            FirstName = "Pren",
                            LastName = "Handsheart",
                            Telephone = "696-166-9385"
                        },
                        new
                        {
                            Id = 2,
                            Address = "909 Evergreen Trail",
                            City = "Hatton",
                            FirstName = "Heinrick",
                            LastName = "Vanyatin",
                            Telephone = "832-116-9214"
                        },
                        new
                        {
                            Id = 3,
                            Address = "81 Canary Hill",
                            City = "Guangfu",
                            FirstName = "Ivie",
                            LastName = "Casterton",
                            Telephone = "922-605-4531"
                        },
                        new
                        {
                            Id = 4,
                            Address = "784 Everett Circle",
                            City = "Waingapu",
                            FirstName = "Gillian",
                            LastName = "Bissex",
                            Telephone = "312-263-8087"
                        },
                        new
                        {
                            Id = 5,
                            Address = "54695 Farmco Road",
                            City = "Xinzhuang",
                            FirstName = "Pru",
                            LastName = "Geraudy",
                            Telephone = "583-126-3845"
                        },
                        new
                        {
                            Id = 6,
                            Address = "8541 Haas Park",
                            City = "Stěžery",
                            FirstName = "Garry",
                            LastName = "Sulley",
                            Telephone = "737-234-1982"
                        },
                        new
                        {
                            Id = 7,
                            Address = "99708 Onsgard Drive",
                            City = "Tucuran",
                            FirstName = "Allyn",
                            LastName = "McRannell",
                            Telephone = "448-570-8995"
                        },
                        new
                        {
                            Id = 8,
                            Address = "10117 Grasskamp Lane",
                            City = "Benito Juarez",
                            FirstName = "Dugald",
                            LastName = "Vivyan",
                            Telephone = "327-144-9061"
                        },
                        new
                        {
                            Id = 9,
                            Address = "23 Northfield Crossing",
                            City = "Araruama",
                            FirstName = "Christiano",
                            LastName = "Volkes",
                            Telephone = "592-655-7603"
                        },
                        new
                        {
                            Id = 10,
                            Address = "3027 Monterey Court",
                            City = "Samdo",
                            FirstName = "Horatia",
                            LastName = "Tobin",
                            Telephone = "268-859-3203"
                        },
                        new
                        {
                            Id = 11,
                            Address = "7 Heffernan Pass",
                            City = "Angono",
                            FirstName = "Vitia",
                            LastName = "Copins",
                            Telephone = "305-416-2369"
                        },
                        new
                        {
                            Id = 12,
                            Address = "1 Clarendon Road",
                            City = "Beskolen",
                            FirstName = "Agata",
                            LastName = "Sleith",
                            Telephone = "663-555-7609"
                        },
                        new
                        {
                            Id = 13,
                            Address = "68701 Anderson Crossing",
                            City = "Kingsport",
                            FirstName = "Georgeanne",
                            LastName = "Conachy",
                            Telephone = "423-820-4682"
                        },
                        new
                        {
                            Id = 14,
                            Address = "315 Hansons Circle",
                            City = "Philadelphia",
                            FirstName = "Lenora",
                            LastName = "Euesden",
                            Telephone = "610-294-5983"
                        },
                        new
                        {
                            Id = 15,
                            Address = "756 Forest Run Road",
                            City = "Opatów",
                            FirstName = "Bonni",
                            LastName = "Aspland",
                            Telephone = "836-500-7512"
                        },
                        new
                        {
                            Id = 16,
                            Address = "48 Cottonwood Trail",
                            City = "Pragen Selatan",
                            FirstName = "Gael",
                            LastName = "McCuaig",
                            Telephone = "533-212-7915"
                        },
                        new
                        {
                            Id = 17,
                            Address = "16347 Dapin Drive",
                            City = "Ruzhany",
                            FirstName = "Anatola",
                            LastName = "Ashdown",
                            Telephone = "709-337-1856"
                        },
                        new
                        {
                            Id = 18,
                            Address = "9287 Schlimgen Lane",
                            City = "Dalovice",
                            FirstName = "Maritsa",
                            LastName = "Kimber",
                            Telephone = "515-695-3036"
                        },
                        new
                        {
                            Id = 19,
                            Address = "729 Glendale Court",
                            City = "San Juan",
                            FirstName = "Lorilee",
                            LastName = "Frensche",
                            Telephone = "152-194-4906"
                        },
                        new
                        {
                            Id = 20,
                            Address = "98 Melrose Terrace",
                            City = "Uralo-Kavkaz",
                            FirstName = "Merola",
                            LastName = "Impey",
                            Telephone = "663-393-2782"
                        },
                        new
                        {
                            Id = 21,
                            Address = "28 Sundown Hill",
                            City = "Smokvica",
                            FirstName = "Mendy",
                            LastName = "Reville",
                            Telephone = "550-121-5868"
                        },
                        new
                        {
                            Id = 22,
                            Address = "2 Waubesa Circle",
                            City = "Seattle",
                            FirstName = "Raymond",
                            LastName = "Darlison",
                            Telephone = "253-838-1723"
                        },
                        new
                        {
                            Id = 23,
                            Address = "101 Scoville Avenue",
                            City = "Hongkou",
                            FirstName = "Tyrus",
                            LastName = "Dumingo",
                            Telephone = "423-329-2153"
                        },
                        new
                        {
                            Id = 24,
                            Address = "278 Lake View Trail",
                            City = "Les Abymes",
                            FirstName = "Riannon",
                            LastName = "Heigold",
                            Telephone = "628-704-9463"
                        },
                        new
                        {
                            Id = 25,
                            Address = "538 Loomis Circle",
                            City = "Nueva Loja",
                            FirstName = "Flin",
                            LastName = "Witherup",
                            Telephone = "664-206-1619"
                        },
                        new
                        {
                            Id = 26,
                            Address = "62 Parkside Alley",
                            City = "Herceg-Novi",
                            FirstName = "Mateo",
                            LastName = "Schumacher",
                            Telephone = "386-444-3002"
                        },
                        new
                        {
                            Id = 27,
                            Address = "164 Meadow Valley Street",
                            City = "Fudian",
                            FirstName = "Marthe",
                            LastName = "Bollen",
                            Telephone = "665-819-7193"
                        },
                        new
                        {
                            Id = 28,
                            Address = "1854 Declaration Street",
                            City = "Bambakashat",
                            FirstName = "Seumas",
                            LastName = "Indruch",
                            Telephone = "325-590-1515"
                        },
                        new
                        {
                            Id = 29,
                            Address = "0 Farragut Street",
                            City = "Pameungpeuk",
                            FirstName = "Kenneth",
                            LastName = "Gason",
                            Telephone = "238-235-9796"
                        },
                        new
                        {
                            Id = 30,
                            Address = "4586 Shelley Street",
                            City = "Ratíškovice",
                            FirstName = "Kurt",
                            LastName = "Bagwell",
                            Telephone = "512-185-9090"
                        },
                        new
                        {
                            Id = 31,
                            Address = "59303 Fallview Road",
                            City = "Kawakawa",
                            FirstName = "Alf",
                            LastName = "Travis",
                            Telephone = "655-453-5195"
                        },
                        new
                        {
                            Id = 32,
                            Address = "767 Golf Center",
                            City = "Kaburon",
                            FirstName = "Stanislas",
                            LastName = "Swadlin",
                            Telephone = "649-852-8037"
                        },
                        new
                        {
                            Id = 33,
                            Address = "11894 Starling Point",
                            City = "Gusinoozyorsk",
                            FirstName = "Kerrill",
                            LastName = "Brokenshaw",
                            Telephone = "395-777-1951"
                        },
                        new
                        {
                            Id = 34,
                            Address = "1 Bay Drive",
                            City = "Tamanan",
                            FirstName = "Holly-anne",
                            LastName = "Whitley",
                            Telephone = "625-587-0047"
                        },
                        new
                        {
                            Id = 35,
                            Address = "84285 Loeprich Park",
                            City = "Lasi Dua",
                            FirstName = "Elmore",
                            LastName = "Doley",
                            Telephone = "761-532-2032"
                        },
                        new
                        {
                            Id = 36,
                            Address = "51910 Monterey Drive",
                            City = "Kommunisticheskiy",
                            FirstName = "Farly",
                            LastName = "Thurley",
                            Telephone = "195-822-2832"
                        },
                        new
                        {
                            Id = 37,
                            Address = "201 Stang Court",
                            City = "Safotu",
                            FirstName = "Stephi",
                            LastName = "Shellibeer",
                            Telephone = "201-201-0649"
                        },
                        new
                        {
                            Id = 38,
                            Address = "6 Superior Terrace",
                            City = "Dayou",
                            FirstName = "Mortie",
                            LastName = "Gypps",
                            Telephone = "134-686-0873"
                        },
                        new
                        {
                            Id = 39,
                            Address = "5 Hagan Avenue",
                            City = "Trzebieszów",
                            FirstName = "Petey",
                            LastName = "Apthorpe",
                            Telephone = "227-148-6992"
                        },
                        new
                        {
                            Id = 40,
                            Address = "19 Declaration Hill",
                            City = "Sanhui",
                            FirstName = "Hyacinthe",
                            LastName = "Chidler",
                            Telephone = "873-931-9819"
                        },
                        new
                        {
                            Id = 41,
                            Address = "8 Boyd Court",
                            City = "Ulyanovsk",
                            FirstName = "Mellicent",
                            LastName = "de Nore",
                            Telephone = "770-120-0778"
                        },
                        new
                        {
                            Id = 42,
                            Address = "4626 Northport Avenue",
                            City = "Irbid",
                            FirstName = "Karney",
                            LastName = "Botton",
                            Telephone = "106-322-9032"
                        },
                        new
                        {
                            Id = 43,
                            Address = "67289 Mesta Hill",
                            City = "Gaotieling",
                            FirstName = "Johanna",
                            LastName = "Seabrooke",
                            Telephone = "991-485-2169"
                        });
                });

            modelBuilder.Entity("PetClinic.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("OwnerId");

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Inessa",
                            OwnerId = 10,
                            Type = (short)5
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2012, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ulrika",
                            OwnerId = 36,
                            Type = (short)2
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2018, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Babita",
                            OwnerId = 26,
                            Type = (short)2
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cloris",
                            OwnerId = 28,
                            Type = (short)3
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2004, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charla",
                            OwnerId = 35,
                            Type = (short)5
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2015, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jeanna",
                            OwnerId = 5,
                            Type = (short)5
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2013, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Haley",
                            OwnerId = 41,
                            Type = (short)6
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2011, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucie",
                            OwnerId = 41,
                            Type = (short)4
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2016, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gunner",
                            OwnerId = 24,
                            Type = (short)6
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2012, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paten",
                            OwnerId = 18,
                            Type = (short)3
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2006, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adrian",
                            OwnerId = 10,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2010, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abbot",
                            OwnerId = 10,
                            Type = (short)3
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2013, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shelagh",
                            OwnerId = 9,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2006, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Briant",
                            OwnerId = 5,
                            Type = (short)6
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2014, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clo",
                            OwnerId = 38,
                            Type = (short)2
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2016, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Franny",
                            OwnerId = 37,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2006, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kylie",
                            OwnerId = 27,
                            Type = (short)3
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2004, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Niccolo",
                            OwnerId = 29,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2007, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charo",
                            OwnerId = 26,
                            Type = (short)3
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2015, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abelard",
                            OwnerId = 40,
                            Type = (short)5
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(2013, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hillyer",
                            OwnerId = 38,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(2014, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Roma",
                            OwnerId = 37,
                            Type = (short)4
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Edithe",
                            OwnerId = 14,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2008, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Celinda",
                            OwnerId = 27,
                            Type = (short)2
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(2017, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Silvia",
                            OwnerId = 22,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2012, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mattie",
                            OwnerId = 10,
                            Type = (short)4
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2017, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Katherine",
                            OwnerId = 10,
                            Type = (short)4
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(2007, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maryann",
                            OwnerId = 20,
                            Type = (short)1
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(2010, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikita",
                            OwnerId = 12,
                            Type = (short)4
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(2017, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elke",
                            OwnerId = 11,
                            Type = (short)2
                        });
                });

            modelBuilder.Entity("PetClinic.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dentistry"
                        });
                });

            modelBuilder.Entity("PetClinic.Models.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jacintha",
                            LastName = "Runham"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tadeas",
                            LastName = "Rockcliff"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Urbain",
                            LastName = "Wasson"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Milton",
                            LastName = "Branson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Hildagard",
                            LastName = "Lintot"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Aristotle",
                            LastName = "Blyde"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Jacquenetta",
                            LastName = "Aleksidze"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Viviana",
                            LastName = "Storre"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Kali",
                            LastName = "Kennet"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Alick",
                            LastName = "Ornils"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Robin",
                            LastName = "Form"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Petronille",
                            LastName = "Montfort"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Beverlie",
                            LastName = "Meaking"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Barnett",
                            LastName = "Simpole"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Dougy",
                            LastName = "Orteu"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Tallie",
                            LastName = "Fanstone"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Chico",
                            LastName = "Aslie"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Lauren",
                            LastName = "Dibley"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Reginauld",
                            LastName = "Gercken"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Dayle",
                            LastName = "MacGiffin"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Maren",
                            LastName = "Degoey"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Em",
                            LastName = "D'Angeli"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Devlin",
                            LastName = "Tompkins"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Rubetta",
                            LastName = "Syder"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Olive",
                            LastName = "Laffoley-Lane"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Markus",
                            LastName = "Lydster"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Ritchie",
                            LastName = "Girardey"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Goldarina",
                            LastName = "Greensides"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Jonell",
                            LastName = "Earland"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Chiquita",
                            LastName = "Spandley"
                        });
                });

            modelBuilder.Entity("PetClinic.Models.VetSpecialty", b =>
                {
                    b.Property<int>("VetId");

                    b.Property<int>("SpecialtyId");

                    b.HasKey("VetId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("VetSpecialties");

                    b.HasData(
                        new
                        {
                            VetId = 1,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 2,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 3,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 4,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 5,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 6,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 7,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 8,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 9,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 10,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 11,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 12,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 13,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 14,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 15,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 16,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 17,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 18,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 19,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 20,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 21,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 22,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 23,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 24,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 25,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 26,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 27,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 28,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 29,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 30,
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("PetClinic.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("PetId");

                    b.Property<int>("VetId");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VetId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2006, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 1,
                            VetId = 18
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2003, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 2,
                            VetId = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2017, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 3,
                            VetId = 16
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2017, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 4,
                            VetId = 10
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2011, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 5,
                            VetId = 3
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2008, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 6,
                            VetId = 1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2013, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 7,
                            VetId = 11
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2004, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 8,
                            VetId = 11
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2006, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 9,
                            VetId = 24
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2010, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 10,
                            VetId = 13
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2016, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 11,
                            VetId = 8
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2007, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 12,
                            VetId = 27
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2011, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 13,
                            VetId = 29
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2001, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 14,
                            VetId = 23
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2014, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 15,
                            VetId = 30
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2006, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 16,
                            VetId = 28
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2008, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 17,
                            VetId = 3
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2009, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 18,
                            VetId = 21
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2008, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 19,
                            VetId = 15
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2018, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 20,
                            VetId = 15
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2002, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 21,
                            VetId = 9
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2005, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 22,
                            VetId = 6
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2012, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 23,
                            VetId = 11
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2005, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 24,
                            VetId = 2
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2003, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 25,
                            VetId = 18
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2011, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 26,
                            VetId = 10
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2014, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 27,
                            VetId = 15
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2012, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 28,
                            VetId = 12
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2009, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 29,
                            VetId = 24
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2003, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            PetId = 30,
                            VetId = 28
                        });
                });

            modelBuilder.Entity("PetClinic.Models.Pet", b =>
                {
                    b.HasOne("PetClinic.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PetClinic.Models.VetSpecialty", b =>
                {
                    b.HasOne("PetClinic.Models.Specialty", "Specialty")
                        .WithMany("VetSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetClinic.Models.Vet", "Vet")
                        .WithMany("Specialties")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PetClinic.Models.Visit", b =>
                {
                    b.HasOne("PetClinic.Models.Pet", "Pet")
                        .WithMany("Visits")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetClinic.Models.Vet", "AssignedVet")
                        .WithMany("Visits")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
